# Google play store dataset 

In [1]:
import pandas as pd
import numpy as np
PATH = "googleplaystore.csv"
df = pd.read_csv(PATH)

In [2]:
len(df)

10841

In [3]:
df.head(10)

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   
5                         Paper flowers instructions  ART_AND_DESIGN     4.4   
6            Smoke Effect Photo Maker - Smoke Editor  ART_AND_DESIGN     3.8   
7                                   Infinite Painter  ART_AND_DESIGN     4.1   
8                               Garden Coloring Book  ART_AND_DESIGN     4.4   
9                      Kids Paint Free - Drawing Fun  ART_AND_DESIGN     4.7   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   
5     167  5.6M      50,000+  Free     0       Everyone   
6     178   19M      50,000+  Free     0       Everyone   
7   36815   29M   1,000,000+  Free     0       Everyone   
8   13791   33M   1,000,000+  Free     0       Everyone   
9     121  3.1M      10,000+  Free     0       Everyone   

                      Genres        Last Updated         Current Ver  \
0               Art & Design     January 7, 2018               1.0.0   
1  Art & Design;Pretend Play    January 15, 2018               2.0.0   
2               Art & Design      August 1, 2018               1.2.4   
3               Art & Design        June 8, 2018  Varies with device   
4    Art & Design;Creativity       June 20, 2018                 1.1   
5               Art & Design      March 26, 2017                 1.0   
6               Art & Design      April 26, 2018                 1.1   
7               Art & Design       June 14, 2018            6.1.61.1   
8               Art & Design  September 20, 2017               2.9.2   
9    Art & Design;Creativity        July 3, 2018                 2.8   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up  
5    2.3 and up  
6  4.0.3 and up  
7    4.2 and up  
8    3.0 and up  
9  4.0.3 and up

In [4]:
len(df["Category"].unique())

34

In [5]:
len(df["Genres"].unique()) 
# lets drop genres column that sounds a duplicate with "Category" column 

120

In [6]:
df["Rating"].value_counts(dropna=False)
# think about what to do with that many NaN values and delete the only redundant value:"19.0"

NaN      1474
 4.4     1109
 4.3     1076
 4.5     1038
 4.2      952
 4.6      823
 4.1      708
 4.0      568
 4.7      499
 3.9      386
 3.8      303
 5.0      274
 3.7      239
 4.8      234
 3.6      174
 3.5      163
 3.4      128
 3.3      102
 4.9       87
 3.0       83
 3.1       69
 3.2       64
 2.9       45
 2.8       42
 2.6       25
 2.7       25
 2.5       21
 2.3       20
 2.4       19
 1.0       16
 2.2       14
 1.9       13
 2.0       12
 1.8        8
 1.7        8
 2.1        8
 1.6        4
 1.5        3
 1.4        3
 1.2        1
 19.0       1
Name: Rating, dtype: int64

In [7]:
df["Price"].value_counts()

0           10040
$0.99         148
$2.99         129
$1.99          73
$4.99          72
$3.99          63
$1.49          46
$5.99          30
$2.49          26
$9.99          21
$6.99          13
$399.99        12
$14.99         11
$4.49           9
$7.99           7
$3.49           7
$24.99          7
$29.99          7
$19.99          6
$5.49           6
$11.99          5
$12.99          5
$8.99           5
$6.49           5
$16.99          3
$1.00           3
$2.00           3
$10.00          3
$33.99          2
$3.95           2
            ...  
$74.99          1
$394.99         1
$19.90          1
$46.99          1
$30.99          1
$15.99          1
$1.20           1
$2.56           1
$28.99          1
$154.99         1
$37.99          1
$109.99         1
$3.08           1
$1.61           1
$4.84           1
$2.95           1
$2.50           1
$1.26           1
$14.00          1
$4.29           1
$4.60           1
$89.99          1
Everyone        1
$3.88           1
$1.96     

In [8]:
# what makes the most installing of the app?

In [9]:
df["Content Rating"].value_counts(dropna=False)

Everyone           8714
Teen               1208
Mature 17+          499
Everyone 10+        414
Adults only 18+       3
Unrated               2
NaN                   1
Name: Content Rating, dtype: int64

In [10]:
# df["Android Ver"].value_counts(dropna=False)

In [11]:
df["Type"].value_counts(dropna=False)
# I need to drop nan and 0 values

Free    10039
Paid      800
0           1
NaN         1
Name: Type, dtype: int64

In [12]:
df["Size"].dtypes

dtype('O')

In [13]:
df["Size"].value_counts()
len(df[df["Size"] == "Varies with device"])/len(df["Size"])
# I am gonna replace "varies with device" with zero, since I can make assumption the size of the apps 

# df["Size"].replace("Varies with device", "0M", inplace=True)

0.15635089013928605

In [14]:
# dropping garbage
df = df[df["Size"] != "1,000+"]

In [15]:



# len(df[df["Size"] == "0M"])

# len(df[df["Size"] == "0M"])

In [16]:
# df["Size"] = df["Size"].apply(lambda x: x[:-1] if "k" not in x)


In [17]:
# df["Size"]= df["Size"].apply(lambda x: x[:-1])

In [18]:
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [19]:
len(df[df["Installs"]=="1,000,000,000+"])

58

In [20]:
df[df["App"] == "Facebook"]

App Category  Rating   Reviews                Size        Installs  \
2544  Facebook   SOCIAL     4.1  78158306  Varies with device  1,000,000,000+   
3943  Facebook   SOCIAL     4.1  78128208  Varies with device  1,000,000,000+   

      Type Price Content Rating  Genres    Last Updated         Current Ver  \
2544  Free     0           Teen  Social  August 3, 2018  Varies with device   
3943  Free     0           Teen  Social  August 3, 2018  Varies with device   

             Android Ver  
2544  Varies with device  
3943  Varies with device

In [21]:
df.duplicated("App").value_counts()

False    9659
True     1181
dtype: int64

In [22]:
#### Dropped duplicated values and keep only first one for better outputs

In [23]:
df.drop_duplicates(subset=["App"], keep='first', inplace=True)

In [24]:
df.duplicated("App").value_counts()

False    9659
dtype: int64

In [25]:
df[df["App"] == "Facebook"]

App Category  Rating   Reviews                Size        Installs  \
2544  Facebook   SOCIAL     4.1  78158306  Varies with device  1,000,000,000+   

      Type Price Content Rating  Genres    Last Updated         Current Ver  \
2544  Free     0           Teen  Social  August 3, 2018  Varies with device   

             Android Ver  
2544  Varies with device

In [26]:
df["Last Updated"].unique()

array(['January 7, 2018', 'January 15, 2018', 'August 1, 2018', ...,
       'January 20, 2014', 'February 16, 2014', 'March 23, 2014'],
      dtype=object)

### Converting date from string into date object 

In [27]:
df["Last Updated"] = pd.to_datetime(df['Last Updated'])

In [28]:
df[df["App"] == "Facebook"]

App Category  Rating   Reviews                Size        Installs  \
2544  Facebook   SOCIAL     4.1  78158306  Varies with device  1,000,000,000+   

      Type Price Content Rating  Genres Last Updated         Current Ver  \
2544  Free     0           Teen  Social   2018-08-03  Varies with device   

             Android Ver  
2544  Varies with device

In [29]:
# final_2016.sort_values(by=["Week", "Location"], inplace=True)
# resettin the indexes
# df.reset_index(drop=True, inplace=True)
# df.head()

## More Cleaning To-Do List:
####    1. Remove unnecessary characters from "Installs" column and convert to int
####    2. Convert string to int columns=["Rating", "Price", "Reviews"]
####    3. Replace "NaN" values with 0 int in "Rating"
####    4. Drop Genres column it is almost a duplicate of Category

In [30]:
# Dropping unused columns
df.drop(columns=["Genres", "Current Ver", "Android Ver"], inplace=True)

In [31]:
df["Installs"].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0'], dtype=object)

In [32]:
# Dropping non used value
df = df[df["Installs"] != "0"]

In [33]:
df["Installs"] = df["Installs"].apply(lambda x: x[:-1])


In [34]:
df["Installs"].unique()

array(['10,000', '500,000', '5,000,000', '50,000,000', '100,000',
       '50,000', '1,000,000', '10,000,000', '5,000', '100,000,000',
       '1,000,000,000', '1,000', '500,000,000', '50', '100', '500', '10',
       '1', '5', '0'], dtype=object)

In [35]:
# removing commas and converting to int
df["Installs"] = df["Installs"].apply(lambda x: int(x.replace(',','')))


In [36]:
df["Price"].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [37]:
# Converting price from str to float
df["Price"].replace("0", "$0", inplace=True)
df["Price"] = df["Price"].apply(lambda x: x[1:]).astype(float).round(2)

In [38]:
df["Price"].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [39]:
df["Rating"] = df["Rating"].fillna(0).astype(float)

In [40]:
df["Rating"].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , 0. , 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [41]:
df["Reviews"] = df["Reviews"].astype(int)

In [42]:
df[df["App"] == "Facebook"]

App Category  Rating   Reviews                Size    Installs  \
2544  Facebook   SOCIAL     4.1  78158306  Varies with device  1000000000   

      Type  Price Content Rating Last Updated  
2544  Free    0.0           Teen   2018-08-03

In [43]:
df["Reviews"].unique()

array([   159,    967,  87510, ...,    603,   1195, 398307])

In [44]:
# resetting indecies after cleaning
df.reset_index(drop=True, inplace=True)